name: Pluralsight CICD  

on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    types: ['opened', 'synchronize']

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    
    - name: Restore Dependencies
      run: dotnet restore

    - id: build
      name: Build      
      run: dotnet build --no-restore

    - run: ls -la 

    - id: test
      name: Test
      run: dotnet test "PluralsightApi.Tests/PluralsightApi.Tests.csproj" --collect "XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura

    - id: coverage
      name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: PluralsightApi.Tests/TestResults/**/coverage.cobertura.xml
        badge: false
        fail_below_min: false        
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: console
